builds:
  - binary: boondoggle
    goos:
      - darwin
      - linux
    goarch:
      - amd64

brew:
  name: boondoggle
  github:
    owner: gmorse81
    name: homebrew-boondoggle

  commit_author:
    name: gmorse81
    email: gmorse81@gmail.com

